import React, { ReactNode } from "react";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/components/BootstrapClient.js";
import "bootstrap-icons/font/bootstrap-icons.css"; // Import Bootstrap Icons CSS
import "./globals.css";
import { Inter } from "next/font/google";
/* eslint-disable react/no-unescaped-entities */

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chris Ge",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
